<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'first_name' => 'Jan',
                'last_name' => 'Kowalski',
                'phone' => '+48501234567',
                'email' => 'jan.kowalski@example.com',
                'password' => Hash::make('password123'),
                'role' => 'admin',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Anna',
                'last_name' => 'Nowak',
                'phone' => '+48502345678',
                'email' => 'anna.nowak@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Piotr',
                'last_name' => 'Wiśniewski',
                'phone' => '+48503456789',
                'email' => 'piotr.wisniewski@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Maria',
                'last_name' => 'Wójcik',
                'phone' => '+48504567890',
                'email' => 'maria.wojcik@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Krzysztof',
                'last_name' => 'Kowalczyk',
                'phone' => '+48505678901',
                'email' => 'krzysztof.kowalczyk@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Agnieszka',
                'last_name' => 'Kamińska',
                'phone' => '+48506789012',
                'email' => 'agnieszka.kaminska@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Tomasz',
                'last_name' => 'Lewandowski',
                'phone' => '+48507890123',
                'email' => 'tomasz.lewandowski@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Katarzyna',
                'last_name' => 'Zielińska',
                'phone' => '+48508901234',
                'email' => 'katarzyna.zielinska@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Marcin',
                'last_name' => 'Szymański',
                'phone' => '+48509012345',
                'email' => 'marcin.szymanski@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Joanna',
                'last_name' => 'Woźniak',
                'phone' => '+48510123456',
                'email' => 'joanna.wozniak@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Robert',
                'last_name' => 'Dąbrowski',
                'phone' => '+48511234567',
                'email' => 'robert.dabrowski@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Magdalena',
                'last_name' => 'Góral',
                'phone' => '+48512345678',
                'email' => 'magdalena.goral@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Paweł',
                'last_name' => 'Kozłowski',
                'phone' => '+48513456789',
                'email' => 'pawel.kozlowski@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Ewa',
                'last_name' => 'Jankowska',
                'phone' => '+48514567890',
                'email' => 'ewa.jankowska@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Michał',
                'last_name' => 'Mazur',
                'phone' => '+48515678901',
                'email' => 'michal.mazur@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Barbara',
                'last_name' => 'Krawczyk',
                'phone' => '+48516789012',
                'email' => 'barbara.krawczyk@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Łukasz',
                'last_name' => 'Piotrowski',
                'phone' => '+48517890123',
                'email' => 'lukasz.piotrowski@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Dorota',
                'last_name' => 'Grabowska',
                'phone' => '+48518901234',
                'email' => 'dorota.grabowska@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Rafał',
                'last_name' => 'Pawłowski',
                'phone' => '+48519012345',
                'email' => 'rafal.pawlowski@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Monika',
                'last_name' => 'Michalska',
                'phone' => '+48520123456',
                'email' => 'monika.michalska@example.com',
                'password' => Hash::make('password123'),
                'role' => 'user',
                'email_verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('users')->insert($users);
    }
}
