version: '3.8'

services:
  webserver:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - property-images:/var/www/html/images/properties  # Wolumin na zdjęcia nieruchomości
    networks:
      - app-network

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: homeiq
      MYSQL_USER: homeiquser
      MYSQL_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  property-images:  # Definicja wolumenu dla zdjęć nieruchomości